# WebRTC-MCU
# git https://github.com/xivistudios/webrtc-mcu
# Copyright(c) 2018-2023 Mr.Panda xivistudios
# MIT Licensed

# http配置
[http]
host = "www.xivistudios.com"
port = 443
origin = "https://www.xivistudios.com"
views = "/root/package/webrtc-mcu/page/html"
public = "/root/package/webrtc-mcu/page/public"

# https证书配置
[https]
key = "/root/cert/www.xivistudios.com.key"
cert = "/root/cert/www.xivistudios.com.pem"

# http session 配置
[session]
name = "authUser"
maxAge = 604800000
keys = [
  "dskaopd8sa908csacu89u9c", 
  "cad8c90a8c8as8cx8a8csac6tc7"
]

# mongodb数据库连接配置
[mongodb]
host = "127.0.0.1"
port = 27017
dbname = "WEBRTCMCU"
document = [
  "admin",
  "log",
  "cluster",
  "apiAuth"
]

# redis数据库连接配置
[redis]
host = "127.0.0.1"
port = 6379
password = "YTg4ZDkyZDQxZTk1OWVhNDIxMTQ4OGM4MWZmOWIyNzcyY2UwYzljNjY1Mzg1MmM1Z"

# 加密配置
[crypto]
type = "aes256"
key = "ZDQxZTQ4OGM4MTg4ZDkYzljNjYIyNzcy"

# 邮件服务配置
[nodemailer]
service = "smtp.qq.com"
host = "smtp.qq.com"
port = 465
secureConnection = true
secure = true

# 邮件服务认证配置
[nodemailer.auth]
user = "1198100147@qq.con"
pass = "bdineybhjivyjeai"

# 管理服务接入端口
[service]
port = 88
router = "/masterApi"

# 日志配置
[log]
path = "/root/log/mcu.log"
